### ISSUE TITLE
'NoneType' object is unsubscriptable

### ISSUE THREAD

**Issue by CPlusPlus17** [metzlar-os/djest#1]
Hello

If I try to count the results I always get this error:
        Traceback (most recent call last):
  File "/var/gui/dev/gui/world/tests.py", line 40, in test_SeasonAdmin
    self.assert_result_count(2)
  File "/var/gui/dev/gui/djest/admin.py", line 10, in assert_result_count
    self.response.context['cl'].result_count,
TypeError: 'NoneType' object is unsubscriptable

Code:
    self.assert_result_count(1)

**Comment by metzlar-os** [comment]
Hi Manuel do you mind posting the whole test function?

It's probably because self.response(.context) is None Make sure you navigate to a changelist page before you count any results. In the example self.get(url) and self.post(url, data) before calling self.assert_result_count(n)

**Comment by CPlusPlus17** [comment]
Hello!

```
class SeasonAdminTestCase(AdminCase):
    def setUp(self):
        (
            self.user_name,
            self.user_pass,
            self.user
        ) = self.create_user(is_staff = True)

        self['Season'] = Season(name='TestingAdmin')
        self['Season'].save()

    def test_SeasonAdmin(self):

        self.assertTrue('Season' in self)
        self.assertTrue(self['Season'].name == 'TestingAdmin')

        self.login(self.user_name, self.user_pass)

        self.get(self.reverse('admin:world_season_changelist'))
        self.assert_result_count(1) # Does not work

        self.post(
            self.reverse('admin:world_season_add'),
            {'name': 'Another example instance'}
        )

        self.assert_result_count(2) # Does not work
```

I tried too the reverse from django.core.urlresolvers import reverse.

I added some debugging, so far the user has permissions and is logged in:

```
User is staff: True
User logged  in: True
```

But after  self.get(reverse('admin:world_season_changelist')) this is the response:

```
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: text/html

<h1>403 Forbidden</h1>
```

Edit:
I gave the user superuser and now it working. Sorry for troubling you!
